class MaintenanceCheckListData {
String? dieselLevel;
String? transmitterBatteryAvailability;
String? engineOil;
String? radiatorWater;
String? hydraulicOilLevel;
String? breatherSmoke;
String? hydraulicLeakage;
String? housingTriconeBitSize;
String? rockMasterGrease;
String? shuttleAssembly;
String? shuttleGrease;
String? rubberTrackTightness;
String? chainTightness;
String? fmcMotorGearOil;
String? trackGearBoxOil;
String? rotationGearBoxOil;
String? thrustGearBox;
String? wiseJaw;
String? driveCheckThread;
String? garagePad;
String? shuttlePad;
String? rodWiper;
String? filterCheck;
String? dieselMileage;
String? rodThickness;
String? odoMeterCalibration;
String? rubberTrackConditions;
String? rubberTrackRoller;
String? battery;
String? switchesLights;
String? tyreAirCheck;
String? oilLevel;
String? airBrake;
String? coolantLevel;
String? engineOilLevel;
String? batteryWaterLevel;
String? airCheckup;
String? meterGauge;
String? gearCroneGear;
String? greasePackage;
String? wheelGrease;
String? tyreCondition;
String? garageUnit1;
String? shockupsAlignment;

MaintenanceCheckListData({this.dieselLevel, this.transmitterBatteryAvailability, this.engineOil, this.radiatorWater, this.hydraulicOilLevel, this.breatherSmoke, this.hydraulicLeakage, this.housingTriconeBitSize, this.rockMasterGrease, this.shuttleAssembly, this.shuttleGrease, this.rubberTrackTightness, this.chainTightness, this.fmcMotorGearOil, this.trackGearBoxOil, this.rotationGearBoxOil, this.thrustGearBox, this.wiseJaw, this.driveCheckThread, this.garagePad, this.shuttlePad, this.rodWiper, this.filterCheck, this.dieselMileage, this.rodThickness, this.odoMeterCalibration, this.rubberTrackConditions, this.rubberTrackRoller, this.battery, this.switchesLights, this.tyreAirCheck, this.oilLevel, this.airBrake, this.coolantLevel, this.engineOilLevel, this.batteryWaterLevel, this.airCheckup, this.meterGauge, this.gearCroneGear, this.greasePackage, this.wheelGrease, this.tyreCondition, this.garageUnit1, this.shockupsAlignment});

MaintenanceCheckListData.fromJson(Map<String, dynamic> json) {
dieselLevel = json['dieselLevel'];
transmitterBatteryAvailability = json['transmitterBatteryAvailability'];
engineOil = json['engineOil'];
radiatorWater = json['radiatorWater'];
hydraulicOilLevel = json['hydraulicOilLevel'];
breatherSmoke = json['breatherSmoke'];
hydraulicLeakage = json['hydraulicLeakage'];
housingTriconeBitSize = json['housingTriconeBitSize'];
rockMasterGrease = json['rockMasterGrease'];
shuttleAssembly = json['shuttleAssembly'];
shuttleGrease = json['shuttleGrease'];
rubberTrackTightness = json['rubberTrackTightness'];
chainTightness = json['chainTightness'];
fmcMotorGearOil = json['fmcMotorGearOil'];
trackGearBoxOil = json['trackGearBoxOil'];
rotationGearBoxOil = json['rotationGearBoxOil'];
thrustGearBox = json['thrustGearBox'];
wiseJaw = json['wiseJaw'];
driveCheckThread = json['driveCheckThread'];
garagePad = json['garagePad'];
shuttlePad = json['shuttlePad'];
rodWiper = json['rodWiper'];
filterCheck = json['filterCheck'];
dieselMileage = json['dieselMileage'];
rodThickness = json['rodThickness'];
odoMeterCalibration = json['odoMeterCalibration'];
rubberTrackConditions = json['rubberTrackConditions'];
rubberTrackRoller = json['rubberTrackRoller'];
battery = json['battery'];
switchesLights = json['switchesLights'];
tyreAirCheck = json['tyreAirCheck'];
oilLevel = json['oilLevel'];
airBrake = json['airBrake'];
coolantLevel = json['coolantLevel'];
engineOilLevel = json['engineOilLevel'];
batteryWaterLevel = json['batteryWaterLevel'];
airCheckup = json['airCheckup'];
meterGauge = json['meterGauge'];
gearCroneGear = json['gearCroneGear'];
greasePackage = json['greasePackage'];
wheelGrease = json['wheelGrease'];
tyreCondition = json['tyreCondition'];
garageUnit1 = json['garageUnit1'];
shockupsAlignment = json['shockupsAlignment'];
}

Map<String, dynamic> toJson() {
final Map<String, dynamic> data = new Map<String, dynamic>();
data['dieselLevel'] = this.dieselLevel;
data['transmitterBatteryAvailability'] = this.transmitterBatteryAvailability;
data['engineOil'] = this.engineOil;
data['radiatorWater'] = this.radiatorWater;
data['hydraulicOilLevel'] = this.hydraulicOilLevel;
data['breatherSmoke'] = this.breatherSmoke;
data['hydraulicLeakage'] = this.hydraulicLeakage;
data['housingTriconeBitSize'] = this.housingTriconeBitSize;
data['rockMasterGrease'] = this.rockMasterGrease;
data['shuttleAssembly'] = this.shuttleAssembly;
data['shuttleGrease'] = this.shuttleGrease;
data['rubberTrackTightness'] = this.rubberTrackTightness;
data['chainTightness'] = this.chainTightness;
data['fmcMotorGearOil'] = this.fmcMotorGearOil;
data['trackGearBoxOil'] = this.trackGearBoxOil;
data['rotationGearBoxOil'] = this.rotationGearBoxOil;
data['thrustGearBox'] = this.thrustGearBox;
data['wiseJaw'] = this.wiseJaw;
data['driveCheckThread'] = this.driveCheckThread;
data['garagePad'] = this.garagePad;
data['shuttlePad'] = this.shuttlePad;
data['rodWiper'] = this.rodWiper;
data['filterCheck'] = this.filterCheck;
data['dieselMileage'] = this.dieselMileage;
data['rodThickness'] = this.rodThickness;
data['odoMeterCalibration'] = this.odoMeterCalibration;
data['rubberTrackConditions'] = this.rubberTrackConditions;
data['rubberTrackRoller'] = this.rubberTrackRoller;
data['battery'] = this.battery;
data['switchesLights'] = this.switchesLights;
data['tyreAirCheck'] = this.tyreAirCheck;
data['oilLevel'] = this.oilLevel;
data['airBrake'] = this.airBrake;
data['coolantLevel'] = this.coolantLevel;
data['engineOilLevel'] = this.engineOilLevel;
data['batteryWaterLevel'] = this.batteryWaterLevel;
data['airCheckup'] = this.airCheckup;
data['meterGauge'] = this.meterGauge;
data['gearCroneGear'] = this.gearCroneGear;
data['greasePackage'] = this.greasePackage;
data['wheelGrease'] = this.wheelGrease;
data['tyreCondition'] = this.tyreCondition;
data['garageUnit1'] = this.garageUnit1;
data['shockupsAlignment'] = this.shockupsAlignment;
return data;
}
}
